// Canonical project catalog. Numbered chronologically — 01 is the oldest,
// the highest number is the most recent. Time runs forward through the catalog.
// Update established_on / latest_release as projects move through their lifecycle.

const D = (y, m, d) => new Date(Date.UTC(y, m - 1, d))

export const PROJECTS = [
  {
    code: '01',
    slug: 'unwyned',
    title: 'Unwyned',
    domain: 'ENOLOGY',
    status: 'DEPLOYED',
    classification: 'A wine discovery system.',
    signal: 'Taste, mapped.',
    description:
      'Unwyned builds a personal flavor topology from your sensory thresholds and uses it to recommend bottles you have not tried but are likely to love. iOS, Android, and web.',
    instances: ['iOS', 'ANDROID', 'WEB'],
    stack: ['FLUTTER', 'SUPABASE'],
    established_on: D(2024, 5, 1),
    latest_release: D(2026, 4, 12),
    logo: '/project-unwyned.png',
    links: [
      { label: 'WEBSITE', href: 'https://unwyned.com' },
    ],
    primary_link: 'https://unwyned.com',
  },
  {
    code: '02',
    slug: 'sequentyol',
    title: 'Sequentyol',
    domain: 'NUMBER THEORY',
    status: 'DEPLOYED',
    classification: 'A sequence exploration surface.',
    signal: 'Numbers, plotted patiently.',
    description:
      'Sequentyol is a public mathematics surface for exploring integer sequences and their structure — a slow instrument for reading patterns that live in the OEIS and beyond.',
    instances: ['WEB'],
    stack: ['NEXT.JS', 'POSTGRES'],
    established_on: D(2024, 7, 20),
    latest_release: D(2026, 2, 14),
    logo: '/project-sequentyol.png',
    links: [
      { label: 'WEBSITE', href: 'https://sequentyol.com' },
    ],
    primary_link: 'https://sequentyol.com',
  },
  {
    code: '03',
    slug: 'inceptyon',
    title: 'INCEPTYON',
    subtitle: 'JOVIAN SYSTEM',
    domain: 'SPECULATIVE BIOLOGY',
    status: 'DEPLOYED',
    classification: 'A speculative biology game.',
    signal: 'Tend the moons of an alien Jupiter.',
    description:
      'A meditative simulation of speculative ecosystems on the moons of an alien gas giant. Your job is observation and small interventions; the game is what the system does back.',
    instances: ['iOS', 'ANDROID'],
    stack: ['FLUTTER'],
    established_on: D(2024, 10, 15),
    latest_release: D(2026, 3, 28),
    logo: '/project-inceptyon.png',
    links: [
      { label: 'APP STORE', href: 'https://apps.apple.com/us/app/incept%C3%BFon/id6753733758' },
    ],
    primary_link: 'https://apps.apple.com/us/app/incept%C3%BFon/id6753733758',
  },
  {
    code: '04',
    slug: 'gargantua',
    title: 'Gargantua',
    domain: 'SYSTEM HYGIENE',
    status: 'IN-DEVELOPMENT',
    classification: 'A native macOS system cleaner.',
    signal: 'Quiet machines.',
    description:
      'A native macOS cleaner driven by YAML safety rules and explained on-device by an MLX model. Designed for users who would rather read why a file is being deleted than trust a button.',
    instances: ['macOS'],
    stack: ['SWIFT', 'MLX', 'YAML'],
    established_on: D(2025, 1, 8),
    latest_release: D(2026, 4, 5),
    logo: '/project-gargantua.png',
    links: [
      { label: 'GITHUB', href: 'https://github.com/inceptyon-labs/gargantua' },
    ],
    primary_link: 'https://github.com/inceptyon-labs/gargantua',
  },
  {
    code: '05',
    slug: 'mise',
    title: 'Mise',
    domain: 'CULINARY OPS',
    status: 'DEPLOYED',
    classification: 'Mise en place, software.',
    signal: 'Kitchen-ready, before the kitchen.',
    description:
      'A grocery and meal planner that treats home cooking as a small operations problem. Lists, recipes, weekly plans, and local store deals — everything ready before the kitchen turns on.',
    instances: ['iOS'],
    stack: ['SWIFT', 'SWIFTDATA'],
    established_on: D(2025, 3, 10),
    latest_release: D(2026, 4, 18),
    logo: '/project-mise.png',
    links: [
      { label: 'APP STORE', href: 'https://apps.apple.com/us/app/mise-from-list-to-table/id6761640072' },
    ],
    primary_link: 'https://apps.apple.com/us/app/mise-from-list-to-table/id6761640072',
  },
  {
    code: '06',
    slug: 'gigabrain',
    title: 'GigaBrain',
    subtitle: 'GIGAVERSE CONTROLLER',
    domain: 'GAME AUTOMATION',
    status: 'ACTIVE',
    classification: 'Game automation control.',
    signal: 'Run dungeons while you sleep.',
    description:
      'A Gigaverse dungeon-run controller. Automates progress through routines you would otherwise grind manually, with a dashboard for queues, runs, and outcomes.',
    instances: ['CLI', 'WEB'],
    stack: ['NEXT.JS', 'NODE', 'POSTGRES'],
    established_on: D(2025, 6, 10),
    latest_release: D(2026, 4, 18),
    logo: '/project-gigabrain.png',
    links: [
      { label: 'WEBSITE', href: 'https://gigabrain-eosin.vercel.app/' },
    ],
    primary_link: 'https://gigabrain-eosin.vercel.app/',
  },
  {
    code: '07',
    slug: 'insomnia',
    title: 'Insomnia',
    domain: 'AGENT MONITORING',
    status: 'ACTIVE',
    classification: 'Agent monitoring.',
    signal: 'The watch that doesn’t.',
    description:
      'A monitoring surface for autonomous agents and prediction-market trading bots. Operator-grade telemetry: positions, faults, drift, and the slow tells that show up before things break.',
    instances: ['DASHBOARD'],
    stack: ['HONO', 'REACT', 'POSTGRES'],
    established_on: D(2025, 9, 5),
    latest_release: D(2026, 4, 22),
    logo: '/project-insomnia.png',
    links: [
      { label: 'GITHUB', href: 'https://github.com/inceptyon-labs/insomnia' },
    ],
    primary_link: 'https://github.com/inceptyon-labs/insomnia',
  },
  {
    code: '08',
    slug: 'lensing',
    title: 'Lensing',
    domain: 'AMBIENT DISPLAY',
    status: 'IN-DEVELOPMENT',
    classification: 'Plugin-driven information dashboard.',
    signal: 'Information, refracted.',
    description:
      'An always-on information dashboard for Raspberry Pi displays. Plugins compose what the room sees: weather, transit, calendar, agent status, anything addressable.',
    instances: ['RASPBERRY PI', 'WEB'],
    stack: ['SVELTEKIT', 'NODE'],
    established_on: D(2025, 11, 12),
    latest_release: D(2026, 4, 9),
    logo: '/project-lensing.png',
    links: [
      { label: 'GITHUB', href: 'https://github.com/inceptyon-labs/lensing' },
    ],
    primary_link: 'https://github.com/inceptyon-labs/lensing',
  },
  {
    code: '09',
    slug: 'xenodex',
    title: 'Xenodex',
    domain: 'GENERATIVE LORE',
    status: 'CONCEPT',
    classification: 'On-chain field guide.',
    signal: 'A field guide to nothing real.',
    description:
      'Generative bestiary for fictional ecosystems, with provenance recorded on-chain. Each entry is a small, named, non-real organism — the catalog is the artifact.',
    instances: ['WEB'],
    stack: ['NEXT.JS', 'WEB3'],
    established_on: D(2025, 12, 1),
    latest_release: D(2026, 3, 30),
    logo: '/project-xenodex.png',
    links: [
      { label: 'GITHUB', href: 'https://github.com/inceptyon-labs/xenodex' },
    ],
    primary_link: 'https://github.com/inceptyon-labs/xenodex',
  },
  {
    code: '10',
    slug: 'gulfcoasthackers',
    title: 'Gulf Coast Hackers',
    subtitle: 'GCHL',
    domain: 'FANTASY GOLF',
    status: 'DEPLOYED',
    classification: 'Golf league management with fantasy.',
    signal: 'A league, scored and seeded.',
    description:
      'A full-stack golf league platform with fantasy scoring, draft mechanics, and weekly handicap tracking. Built on edge infrastructure so the season runs faster than the round.',
    instances: ['WEB'],
    stack: ['REACT 19', 'HONO', 'CLOUDFLARE', 'NEON'],
    established_on: D(2025, 12, 23),
    latest_release: D(2026, 4, 20),
    logo: '/project-gulfcoasthackers.png',
    links: [
      { label: 'WEBSITE', href: 'https://gulfcoasthackers.com' },
    ],
    primary_link: 'https://gulfcoasthackers.com',
  },
  {
    code: '11',
    slug: 'tenet',
    title: 'Tenet',
    domain: 'AGENT AUDITING',
    status: 'ACTIVE',
    classification: 'Application health auditing for AI agents.',
    signal: 'Trust, but inspect.',
    description:
      'A health auditing suite for AI-agent codebases. Runs across dependencies, secrets, complexity, accessibility, observability, and SOLID adherence — produces a single auditable score.',
    instances: ['DASHBOARD', 'CLAUDE CODE PLUGIN'],
    stack: ['NODE', 'REACT'],
    established_on: D(2026, 1, 14),
    latest_release: D(2026, 4, 21),
    logo: '/project-tenet.png',
    links: [
      { label: 'DASHBOARD', href: 'https://github.com/inceptyon-labs/tenet-dashboard' },
      { label: 'SKILLS', href: 'https://github.com/inceptyon-labs/tenet-skills' },
    ],
    primary_link: 'https://github.com/inceptyon-labs/tenet-dashboard',
  },
  {
    code: '12',
    slug: 'pasiv',
    title: 'PASIV',
    domain: 'AGENT TOOLING',
    status: 'ACTIVE',
    classification: 'Idea-to-implementation extractor.',
    signal: 'Write the system, ship the system.',
    description:
      'A workflow that takes a vague idea and produces a tested, reviewed implementation an agent can ship. Brainstorm, plan, implement, review, merge — all of it auditable.',
    instances: ['CLAUDE CODE PLUGIN'],
    stack: ['CLAUDE CODE'],
    established_on: D(2026, 2, 8),
    latest_release: D(2026, 4, 23),
    logo: '/project-pasiv.png',
    links: [
      { label: 'GITHUB', href: 'https://github.com/inceptyon-labs/PASIV' },
    ],
    primary_link: 'https://github.com/inceptyon-labs/PASIV',
  },
  {
    code: '13',
    slug: 'tars',
    title: 'TARS',
    domain: 'AGENT CONFIG',
    status: 'ACTIVE',
    classification: 'Claude Code configuration manager.',
    signal: 'One profile, many projects.',
    description:
      'A cross-platform desktop manager for Claude Code: plugins, skills, slash commands, agents, hooks, MCP servers, and reusable profiles — all synchronized across projects.',
    instances: ['macOS', 'WIN', 'LINUX'],
    stack: ['TAURI', 'REACT'],
    established_on: D(2026, 3, 4),
    latest_release: D(2026, 4, 24),
    logo: '/project-tars.svg',
    links: [
      { label: 'GITHUB', href: 'https://github.com/inceptyon-labs/TARS' },
    ],
    primary_link: 'https://github.com/inceptyon-labs/TARS',
  },
  {
    code: '14',
    slug: 'foodymerge',
    title: 'FoodieMerge',
    subtitle: 'PLUM HOLLOW',
    domain: 'MERGE-2 GAMING',
    status: 'DEPLOYED',
    classification: 'A cozy merge-2 mobile game.',
    signal: 'Tap, merge, rebuild the town.',
    description:
      'A cozy merge-2 game where players rebuild Plum Hollow by tapping generators, merging board items, fulfilling orders, and unlocking a small farm town. iOS and Android.',
    instances: ['iOS', 'ANDROID'],
    stack: ['FLUTTER'],
    established_on: D(2026, 5, 16),
    latest_release: D(2026, 6, 6),
    logo: '/project-foodymerge.png',
    links: [
      { label: 'WEBSITE', href: 'https://foodiemerge.com' },
      { label: 'APP STORE', href: 'https://apps.apple.com/app/foodiemerge/id6772793633' },
      { label: 'GOOGLE PLAY', href: 'https://play.google.com/store/apps/details?id=com.inceptyonlabs.foodymerge' },
    ],
    primary_link: 'https://foodiemerge.com',
  },
]

export const PROJECT_TOTAL = PROJECTS.length

export function getProject(slug) {
  return PROJECTS.find((p) => p.slug === slug)
}
